/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecipeIndexImport } from './routes/recipe/index'
import { Route as BoardsBoardIdImport } from './routes/boards.$boardId'
import { Route as RecipeRecipeIdIndexImport } from './routes/recipe/$recipeId/index'
import { Route as RecipeRecipeIdVersionVersionImport } from './routes/recipe/$recipeId/version/$version'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipeIndexRoute = RecipeIndexImport.update({
  id: '/recipe/',
  path: '/recipe/',
  getParentRoute: () => rootRoute,
} as any)

const BoardsBoardIdRoute = BoardsBoardIdImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRoute,
} as any)

const RecipeRecipeIdIndexRoute = RecipeRecipeIdIndexImport.update({
  id: '/recipe/$recipeId/',
  path: '/recipe/$recipeId/',
  getParentRoute: () => rootRoute,
} as any)

const RecipeRecipeIdVersionVersionRoute =
  RecipeRecipeIdVersionVersionImport.update({
    id: '/recipe/$recipeId/version/$version',
    path: '/recipe/$recipeId/version/$version',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdImport
      parentRoute: typeof rootRoute
    }
    '/recipe/': {
      id: '/recipe/'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof RecipeIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipe/$recipeId/': {
      id: '/recipe/$recipeId/'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof RecipeRecipeIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipe/$recipeId/version/$version': {
      id: '/recipe/$recipeId/version/$version'
      path: '/recipe/$recipeId/version/$version'
      fullPath: '/recipe/$recipeId/version/$version'
      preLoaderRoute: typeof RecipeRecipeIdVersionVersionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/recipe': typeof RecipeIndexRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdIndexRoute
  '/recipe/$recipeId/version/$version': typeof RecipeRecipeIdVersionVersionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/recipe': typeof RecipeIndexRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdIndexRoute
  '/recipe/$recipeId/version/$version': typeof RecipeRecipeIdVersionVersionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/recipe/': typeof RecipeIndexRoute
  '/recipe/$recipeId/': typeof RecipeRecipeIdIndexRoute
  '/recipe/$recipeId/version/$version': typeof RecipeRecipeIdVersionVersionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards/$boardId'
    | '/recipe'
    | '/recipe/$recipeId'
    | '/recipe/$recipeId/version/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards/$boardId'
    | '/recipe'
    | '/recipe/$recipeId'
    | '/recipe/$recipeId/version/$version'
  id:
    | '__root__'
    | '/'
    | '/boards/$boardId'
    | '/recipe/'
    | '/recipe/$recipeId/'
    | '/recipe/$recipeId/version/$version'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  RecipeIndexRoute: typeof RecipeIndexRoute
  RecipeRecipeIdIndexRoute: typeof RecipeRecipeIdIndexRoute
  RecipeRecipeIdVersionVersionRoute: typeof RecipeRecipeIdVersionVersionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  RecipeIndexRoute: RecipeIndexRoute,
  RecipeRecipeIdIndexRoute: RecipeRecipeIdIndexRoute,
  RecipeRecipeIdVersionVersionRoute: RecipeRecipeIdVersionVersionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/boards/$boardId",
        "/recipe/",
        "/recipe/$recipeId/",
        "/recipe/$recipeId/version/$version"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/boards/$boardId": {
      "filePath": "boards.$boardId.tsx"
    },
    "/recipe/": {
      "filePath": "recipe/index.tsx"
    },
    "/recipe/$recipeId/": {
      "filePath": "recipe/$recipeId/index.tsx"
    },
    "/recipe/$recipeId/version/$version": {
      "filePath": "recipe/$recipeId/version/$version.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
